USE tienda;

 SELECT nombre FROM producto;
 SELECT nombre, precio FROM producto;
 SELECT * FROM producto;
 SELECT nombre, precio, ROUND(precio/0.95, 2) FROM producto;
 select nombre as nombre_producto, precio as precio_euro,round(precio/0.95,2) as precio_dolar from producto;
 select upper(nombre), precio from producto;
 select lower(nombre), precio from producto;
 select nombre, upper(left(nombre,2)) from fabricante;
 select nombre, round(precio,1) from producto;
 select nombre, truncate(precio, 0) as precio_nodecimales from producto;
 select codigo_fabricante from producto;
 select distinct codigo_fabricante from producto;
 select nombre from fabricante order by nombre asc;
 select nombre from fabricante order by nombre desc;
 select nombre, precio from producto order by nombre asc, precio desc;
 select * from fabricante limit 5;
 select * from fabricante limit 2 offset 3;
 select nombre, precio from producto order by precio asc limit 1;
 select nombre, precio from producto order by precio desc limit 1;
 select nombre from producto where codigo_fabricante =2;
select p.nombre as nombre_prodcuto , p.precio as precio_producto, f.nombre as nombre_fabricante from producto p join fabricante f on p.codigo_fabricante = f.codigo; 
 select p.nombre as nombre_producto, p.precio as precio_producto, f.nombre as nombre_fabricante from producto p join fabricante f on p.codigo_fabricante=f.codigo order by nombre_fabricante asc;
 select p.codigo as codigo_producto, p.nombre as nombre_producto, f.codigo as codigo_fabricante, f.nombre as nombre_fabricante from producto p join fabricante f on p.codigo_fabricante = f.codigo; 
 select p.nombre as nombre_producto, p.precio as precio_producto, f.nombre as nombre_fabricante from producto p join fabricante f on p.codigo_fabricante=f.codigo order by precio asc limit 1;
 select p.nombre as nombre_producto, p.precio as precio_producto, f.nombre as nombre_fabricante from producto p join fabricante f on p.codigo_fabricante=f.codigo order by precio_producto desc limit 1;
 select p.nombre as nombre_producto,f.nombre as nombre_fabricante from producto p join fabricante f on p.codigo_fabricante =f.codigo where f.nombre = 'Lenovo';
 select p.nombre as nombre_producto, f.nombre as nombre_fabricante from producto p join fabricante f on p.codigo_fabricante = f.codigo where f.nombre='Crucial' and p.precio >200; 
 select p.nombre as nombre_producto, f.nombre as nombre_fabricante from producto p join fabricante f on p.codigo_fabricante=f.codigo where f.nombre = 'Asus' or f.nombre='Hewlett-Packard' or f.nombre='Seagate';
 select p.nombre as nombre_producto, f.nombre as nombre_fabricante from producto p join fabricante f on p.codigo_fabricante=f.codigo where f.nombre in ('Asus', 'Hewlett-Packard', 'Seagate');
 select p.nombre as nombre_producto, p.precio as precio_producto, f.nombre as nombre_fabricante from producto p join fabricante f on p.codigo_fabricante=f.codigo where f.nombre like'%e';
 select p.nombre as nombre_producto, p.precio as precio_producto, f.nombre as nombre_fabricante from producto p join fabricante f on p.codigo_fabricante=f.codigo where f.nombre like'%w%';
 select p.nombre as nombre_prducto, p.precio as precio_producto, f.nombre as nombre_fabricante from producto p join fabricante f on p.codigo_fabricante = f.codigo where p.precio >=180 order by p.precio desc, p.nombre asc;
 select f.codigo as codigo_fabricante, f.nombre as nombre_fabricante from fabricante f join producto p on f.codigo=p.codigo_fabricante;
 select f.nombre as nombre_fabricante, p.nombre as nombre_producto from fabricante f left join producto p on f.codigo=p.codigo_fabricante;
 select f.nombre as nombre_fabricante from fabricante f left join producto p on f.codigo=p.codigo_fabricante where  p.codigo_fabricante is null;
 select nombre from producto where codigo_fabricante = (select codigo from fabricante where nombre ='Lenovo');
 select p.* from producto p where p.precio = ( select max(p2.precio) from producto p2 join fabricante f2 on p2.codigo_fabricante=f2.codigo where f2.nombre='Lenovo');
 select p.nombre as nombre_producto from producto p join fabricante f on p.codigo_fabricante=f.codigo where f.nombre='Lenovo' order by p.precio desc limit 1;
 select p.nombre as nombre_producto from producto p join fabricante f where f.nombre ='Hewlett-Packard' order by p.precio asc limit 1;
 select p.nombre as nombre_producto, p.precio as precio_producto from producto p where p.precio >= ( select max(p.precio) from producto p join fabricante f on p.codigo_fabricante=f.codigo where f.nombre ='Lenovo');
 select p.nombre as nombre_producto, p.precio as precio_producto from producto p join fabricante f where f.nombre = 'Asus' and p.precio>(select avg(p2.precio) from producto p2); 